# This file was generated by rails new with the --api flag, and will be used
# to configure the application for the API-only mode.
#
# Be sure to look at the other files in this directory, including
# application.rb, which contains the Rails application configuration.
#
# See https://guides.rubyonrails.org/application_architecture.html#the-api-flag for
# more information.

# The following line is provided for convenience purposes. It has the downside
# of increasing the boot-up time by auto-requiring all files in the support
# directory. Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
# Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each { |f| require f }

# Configure RSpec
RSpec.configure do |config|
  # Enable flags like --only-failures and --next-failure
  config.example_status_persistence_file_path = ".rspec_status"

  # Disable RSpec exposing methods globally on `Module` and `main`
  config.disable_monkey_patching!

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  # Configure test order
  config.order = :random
  Kernel.srand config.seed

  # Clean up after each test
  config.after(:each) do
    # Clean up any test data if needed
  end

  # Show full backtrace for failures
  config.backtrace_exclusion_patterns = [
    /\/lib\d*\/ruby\//,
    /bin\//,
    /gems/,
    /spec\/spec_helper\.rb/,
    /lib\/rspec\/(core|expectations|mocks)/
  ]
end
